"""Build a dependency-free fallback for the Project Ironwright Mechromancer.

This is intentionally dependency-free so the asset contract can be validated on
machines that do not have Blender installed. The canonical editable source is
the neighboring mechromancer.blend generated by build_mechromancer_blend.py.
The fallback glTF uses the same named nodes and animation clips.
"""

from __future__ import annotations

import base64
import json
import math
import struct
from pathlib import Path
from typing import Iterable, Sequence


ASSET_DIR = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ASSET_DIR / "mechromancer.gltf"


class BufferBuilder:
    def __init__(self) -> None:
        self.data = bytearray()
        self.views: list[dict] = []
        self.accessors: list[dict] = []

    def _align(self) -> None:
        while len(self.data) % 4:
            self.data.append(0)

    def accessor(
        self,
        values: Sequence[float] | Sequence[int],
        component_type: int,
        accessor_type: str,
        count: int,
        target: int | None = None,
        minimum: Sequence[float] | Sequence[int] | None = None,
        maximum: Sequence[float] | Sequence[int] | None = None,
    ) -> int:
        self._align()
        offset = len(self.data)
        if component_type == 5126:
            self.data.extend(struct.pack("<%sf" % len(values), *values))
            component_size = 4
        elif component_type == 5123:
            self.data.extend(struct.pack("<%sH" % len(values), *values))
            component_size = 2
        else:
            raise ValueError(component_type)
        view: dict = {
            "buffer": 0,
            "byteOffset": offset,
            "byteLength": len(self.data) - offset,
        }
        if target is not None:
            view["target"] = target
        view_index = len(self.views)
        self.views.append(view)
        accessor: dict = {
            "bufferView": view_index,
            "componentType": component_type,
            "count": count,
            "type": accessor_type,
        }
        if component_size == 2:
            accessor["normalized"] = False
        if minimum is not None:
            accessor["min"] = list(minimum)
        if maximum is not None:
            accessor["max"] = list(maximum)
        self.accessors.append(accessor)
        return len(self.accessors) - 1


def vec_min_max(values: Iterable[Sequence[float]], width: int = 3) -> tuple[list[float], list[float]]:
    rows = [list(row[:width]) for row in values]
    return (
        [min(row[index] for row in rows) for index in range(width)],
        [max(row[index] for row in rows) for index in range(width)],
    )


def quat(euler_xyz: Sequence[float]) -> list[float]:
    x, y, z = (value * 0.5 for value in euler_xyz)
    cx, sx = math.cos(x), math.sin(x)
    cy, sy = math.cos(y), math.sin(y)
    cz, sz = math.cos(z), math.sin(z)
    return [
        sx * cy * cz - cx * sy * sz,
        cx * sy * cz + sx * cy * sz,
        cx * cy * sz - sx * sy * cz,
        cx * cy * cz + sx * sy * sz,
    ]


def add_box(builder: BufferBuilder, size: Sequence[float], material: int) -> int:
    sx, sy, sz = (value * 0.5 for value in size)
    corners = [
        (-sx, -sy, -sz), (sx, -sy, -sz), (sx, sy, -sz), (-sx, sy, -sz),
        (-sx, -sy, sz), (sx, -sy, sz), (sx, sy, sz), (-sx, sy, sz),
    ]
    faces = [
        ((0, 1, 2, 3), (0.0, 0.0, -1.0)),
        ((5, 4, 7, 6), (0.0, 0.0, 1.0)),
        ((4, 0, 3, 7), (-1.0, 0.0, 0.0)),
        ((1, 5, 6, 2), (1.0, 0.0, 0.0)),
        ((3, 2, 6, 7), (0.0, 1.0, 0.0)),
        ((4, 5, 1, 0), (0.0, -1.0, 0.0)),
    ]
    positions: list[float] = []
    normals: list[float] = []
    indices: list[int] = []
    for face, normal in faces:
        start = len(positions) // 3
        for corner in face:
            positions.extend(corners[corner])
            normals.extend(normal)
        indices.extend([start, start + 1, start + 2, start, start + 2, start + 3])
    position_min, position_max = vec_min_max(zip(*[iter(positions)] * 3))
    position_accessor = builder.accessor(
        positions, 5126, "VEC3", len(positions) // 3, 34962, position_min, position_max
    )
    normal_accessor = builder.accessor(normals, 5126, "VEC3", len(normals) // 3, 34962)
    index_accessor = builder.accessor(indices, 5123, "SCALAR", len(indices), 34963)
    return position_accessor, normal_accessor, index_accessor, material


def add_beveled_box(
    builder: BufferBuilder,
    size: Sequence[float],
    material: int,
    bevel: float = 0.04,
) -> tuple[int, int, int, int]:
    """Build a compact chamfered block for hero-scale field equipment."""
    extents = [max(0.001, value * 0.5) for value in size]
    bevel = min(bevel, min(extents) * 0.42)
    inset = [extent - bevel for extent in extents]
    positions: list[float] = []
    normals: list[float] = []
    indices: list[int] = []

    def add_vertex(point: Sequence[float], normal: Sequence[float]) -> int:
        index = len(positions) // 3
        positions.extend(point)
        normals.extend(normal)
        return index

    def add_quad(points: Sequence[Sequence[float]], normal: Sequence[float]) -> None:
        start = [add_vertex(point, normal) for point in points]
        indices.extend([start[0], start[1], start[2], start[0], start[2], start[3]])

    axis_data = ((0, 1, 2), (1, 2, 0), (2, 0, 1))
    for axis, first, second in axis_data:
        for sign in (-1.0, 1.0):
            face_normal = [0.0, 0.0, 0.0]
            face_normal[axis] = sign
            points: list[list[float]] = []
            for first_sign, second_sign in ((-1.0, -1.0), (1.0, -1.0), (1.0, 1.0), (-1.0, 1.0)):
                point = [0.0, 0.0, 0.0]
                point[axis] = sign * extents[axis]
                point[first] = first_sign * inset[first]
                point[second] = second_sign * inset[second]
                points.append(point)
            add_quad(points, face_normal)

    for axis, first, second in axis_data:
        for first_sign in (-1.0, 1.0):
            for second_sign in (-1.0, 1.0):
                normal = [0.0, 0.0, 0.0]
                normal[axis] = first_sign * 0.70710678
                normal[first] = second_sign * 0.70710678
                points = []
                for remaining_sign in (-1.0, 1.0):
                    point = [0.0, 0.0, 0.0]
                    point[axis] = first_sign * extents[axis]
                    point[first] = second_sign * inset[first]
                    point[second] = remaining_sign * inset[second]
                    points.append(point)
                for remaining_sign in (1.0, -1.0):
                    point = [0.0, 0.0, 0.0]
                    point[axis] = first_sign * inset[axis]
                    point[first] = second_sign * extents[first]
                    point[second] = remaining_sign * inset[second]
                    points.append(point)
                add_quad(points, normal)

    for first_sign in (-1.0, 1.0):
        for second_sign in (-1.0, 1.0):
            for third_sign in (-1.0, 1.0):
                normal = [first_sign * 0.57735027, second_sign * 0.57735027, third_sign * 0.57735027]
                points = [
                    [first_sign * extents[0], second_sign * inset[1], third_sign * inset[2]],
                    [first_sign * inset[0], second_sign * extents[1], third_sign * inset[2]],
                    [first_sign * inset[0], second_sign * inset[1], third_sign * extents[2]],
                ]
                start = [add_vertex(point, normal) for point in points]
                indices.extend([start[0], start[1], start[2]])

    position_min, position_max = vec_min_max(zip(*[iter(positions)] * 3))
    position_accessor = builder.accessor(
        positions, 5126, "VEC3", len(positions) // 3, 34962, position_min, position_max
    )
    normal_accessor = builder.accessor(normals, 5126, "VEC3", len(normals) // 3, 34962)
    index_accessor = builder.accessor(indices, 5123, "SCALAR", len(indices), 34963)
    return position_accessor, normal_accessor, index_accessor, material


HERO_CURVE_SIDES = 24


def add_cylinder(builder: BufferBuilder, radius: float, height: float, material: int, sides: int = 10) -> tuple[int, int, int, int]:
    sides = max(sides, HERO_CURVE_SIDES)
    positions: list[float] = []
    normals: list[float] = []
    indices: list[int] = []
    for ring_y, normal_y in [(-height * 0.5, 0.0), (height * 0.5, 0.0)]:
        for side in range(sides):
            angle = math.tau * side / sides
            positions.extend([math.cos(angle) * radius, ring_y, math.sin(angle) * radius])
            normals.extend([math.cos(angle), normal_y, math.sin(angle)])
    for side in range(sides):
        next_side = (side + 1) % sides
        indices.extend([side, next_side, sides + next_side, side, sides + next_side, sides + side])
    position_min, position_max = vec_min_max(zip(*[iter(positions)] * 3))
    position_accessor = builder.accessor(
        positions, 5126, "VEC3", len(positions) // 3, 34962, position_min, position_max
    )
    normal_accessor = builder.accessor(normals, 5126, "VEC3", len(normals) // 3, 34962)
    index_accessor = builder.accessor(indices, 5123, "SCALAR", len(indices), 34963)
    return position_accessor, normal_accessor, index_accessor, material


def add_cone(builder: BufferBuilder, bottom_radius: float, top_radius: float, height: float, material: int, sides: int = 10) -> tuple[int, int, int, int]:
    sides = max(sides, HERO_CURVE_SIDES)
    positions: list[float] = []
    normals: list[float] = []
    indices: list[int] = []
    slope = (bottom_radius - top_radius) / max(height, 0.001)
    for ring_y, radius in [(-height * 0.5, bottom_radius), (height * 0.5, top_radius)]:
        for side in range(sides):
            angle = math.tau * side / sides
            normal = Vector3(math.cos(angle), slope, math.sin(angle)).normalized()
            positions.extend([math.cos(angle) * radius, ring_y, math.sin(angle) * radius])
            normals.extend([normal.x, normal.y, normal.z])
    for side in range(sides):
        next_side = (side + 1) % sides
        indices.extend([side, next_side, sides + next_side, side, sides + next_side, sides + side])
    position_min, position_max = vec_min_max(zip(*[iter(positions)] * 3))
    position_accessor = builder.accessor(
        positions, 5126, "VEC3", len(positions) // 3, 34962, position_min, position_max
    )
    normal_accessor = builder.accessor(normals, 5126, "VEC3", len(normals) // 3, 34962)
    index_accessor = builder.accessor(indices, 5123, "SCALAR", len(indices), 34963)
    return position_accessor, normal_accessor, index_accessor, material


def add_ellipsoid(
    builder: BufferBuilder,
    scale: Sequence[float],
    material: int,
    rings: int = 16,
    sides: int = 32,
) -> tuple[int, int, int, int]:
    """Build a smooth shallow shell for the dependency-free hero fallback."""
    rings = max(rings, 12)
    sides = max(sides, 24)
    positions: list[float] = []
    normals: list[float] = []
    indices: list[int] = []
    sx, sy, sz = scale
    for ring in range(rings + 1):
        latitude = -math.pi * 0.5 + math.pi * ring / rings
        latitude_cos = math.cos(latitude)
        latitude_sin = math.sin(latitude)
        for side in range(sides):
            longitude = math.tau * side / sides
            longitude_cos = math.cos(longitude)
            longitude_sin = math.sin(longitude)
            positions.extend([
                sx * latitude_cos * longitude_cos,
                sy * latitude_sin,
                sz * latitude_cos * longitude_sin,
            ])
            normal = Vector3(
                latitude_cos * longitude_cos / max(sx, 0.001),
                latitude_sin / max(sy, 0.001),
                latitude_cos * longitude_sin / max(sz, 0.001),
            ).normalized()
            normals.extend([normal.x, normal.y, normal.z])
    for ring in range(rings):
        for side in range(sides):
            next_side = (side + 1) % sides
            a = ring * sides + side
            b = (ring + 1) * sides + side
            c = (ring + 1) * sides + next_side
            d = ring * sides + next_side
            indices.extend([a, b, c, a, c, d])
    position_min, position_max = vec_min_max(zip(*[iter(positions)] * 3))
    position_accessor = builder.accessor(
        positions, 5126, "VEC3", len(positions) // 3, 34962, position_min, position_max
    )
    normal_accessor = builder.accessor(normals, 5126, "VEC3", len(normals) // 3, 34962)
    index_accessor = builder.accessor(indices, 5123, "SCALAR", len(indices), 34963)
    return position_accessor, normal_accessor, index_accessor, material


class Vector3:
    def __init__(self, x: float, y: float, z: float) -> None:
        self.x, self.y, self.z = x, y, z

    def normalized(self) -> "Vector3":
        length = math.sqrt(self.x * self.x + self.y * self.y + self.z * self.z)
        return Vector3(self.x / length, self.y / length, self.z / length)


def main() -> None:
    builder = BufferBuilder()
    materials = [
        {"name": "Worn charcoal coat", "pbrMetallicRoughness": {"baseColorFactor": [0.055, 0.075, 0.09, 1.0], "metallicFactor": 0.05, "roughnessFactor": 0.88}},
        {"name": "Oxidized field metal", "pbrMetallicRoughness": {"baseColorFactor": [0.18, 0.22, 0.24, 1.0], "metallicFactor": 0.72, "roughnessFactor": 0.5}},
        {"name": "Weathered leather", "pbrMetallicRoughness": {"baseColorFactor": [0.18, 0.10, 0.065, 1.0], "metallicFactor": 0.02, "roughnessFactor": 0.9}},
        {"name": "Skin", "pbrMetallicRoughness": {"baseColorFactor": [0.36, 0.25, 0.19, 1.0], "metallicFactor": 0.0, "roughnessFactor": 0.84}},
        {"name": "Cognition cyan", "pbrMetallicRoughness": {"baseColorFactor": [0.06, 0.28, 0.31, 1.0], "metallicFactor": 0.28, "roughnessFactor": 0.3}, "emissiveFactor": [0.12, 0.8, 0.85]},
        {"name": "Warm lamp", "pbrMetallicRoughness": {"baseColorFactor": [0.46, 0.20, 0.06, 1.0], "metallicFactor": 0.12, "roughnessFactor": 0.56}, "emissiveFactor": [0.95, 0.31, 0.08]},
        {"name": "Weak sidearm", "pbrMetallicRoughness": {"baseColorFactor": [0.035, 0.045, 0.05, 1.0], "metallicFactor": 0.82, "roughnessFactor": 0.38}},
    ]
    meshes: list[dict] = []

    def mesh(name: str, geometry: tuple[int, int, int, int]) -> int:
        position, normal, indices, material = geometry
        meshes.append({
            "name": name,
            "primitives": [{"attributes": {"POSITION": position, "NORMAL": normal}, "indices": indices, "material": material}],
        })
        return len(meshes) - 1

    coat = 0
    metal = 1
    leather = 2
    skin = 3
    cyan = 4
    warm = 5
    gun = 6

    mesh_ids = {
        "Torso": mesh("Torso", add_beveled_box(builder, (0.62, 0.72, 0.38), coat, 0.055)),
        "ChestShell": mesh("ChestShell", add_ellipsoid(builder, (0.31, 0.09, 0.27), coat, 16, 32)),
        "ChestArmorPlate": mesh("ChestArmorPlate", add_ellipsoid(builder, (0.24, 0.055, 0.20), metal, 16, 32)),
        "ChestPlate": mesh("ChestPlate", add_beveled_box(builder, (0.48, 0.36, 0.10), metal, 0.025)),
        "Scarf": mesh("Scarf", add_cylinder(builder, 0.22, 0.14, leather, 10)),
        "Hood": mesh("Hood", add_cone(builder, 0.35, 0.22, 0.40, coat, 10)),
        "Face": mesh("Face", add_beveled_box(builder, (0.27, 0.20, 0.12), skin, 0.025)),
        "Visor": mesh("Visor", add_beveled_box(builder, (0.25, 0.045, 0.035), cyan, 0.012)),
        "Shoulder": mesh("Shoulder", add_beveled_box(builder, (0.24, 0.16, 0.34), metal, 0.025)),
        "Pack": mesh("Pack", add_beveled_box(builder, (0.42, 0.52, 0.20), leather, 0.035)),
        "PackPlate": mesh("PackPlate", add_beveled_box(builder, (0.28, 0.20, 0.045), metal, 0.012)),
        "Belt": mesh("Belt", add_beveled_box(builder, (0.58, 0.13, 0.40), leather, 0.025)),
        "Arm": mesh("Arm", add_beveled_box(builder, (0.14, 0.52, 0.16), coat, 0.025)),
        "Glove": mesh("Glove", add_cylinder(builder, 0.095, 0.18, metal, 8)),
        "Leg": mesh("Leg", add_beveled_box(builder, (0.17, 0.64, 0.18), leather, 0.025)),
        "Boot": mesh("Boot", add_beveled_box(builder, (0.22, 0.13, 0.34), metal, 0.025)),
        "CoatTail": mesh("CoatTail", add_beveled_box(builder, (0.27, 0.72, 0.07), coat, 0.018)),
        "Lamp": mesh("Lamp", add_cylinder(builder, 0.085, 0.13, cyan, 8)),
        "LampHousing": mesh("LampHousing", add_beveled_box(builder, (0.16, 0.13, 0.15), metal, 0.02)),
        "Pistol": mesh("Pistol", add_beveled_box(builder, (0.18, 0.12, 0.36), gun, 0.02)),
        "Barrel": mesh("Barrel", add_cylinder(builder, 0.035, 0.26, gun, 8)),
        "Tool": mesh("Tool", add_beveled_box(builder, (0.07, 0.28, 0.07), metal, 0.012)),
        "WarmLamp": mesh("WarmLamp", add_cylinder(builder, 0.045, 0.10, warm, 8)),
        "CommsYoke": mesh("CommsYoke", add_beveled_box(builder, (0.17, 0.13, 0.18), metal, 0.018)),
        "CommsAntenna": mesh("CommsAntenna", add_cylinder(builder, 0.018, 0.27, metal, 10)),
        "CommsBeacon": mesh("CommsBeacon", add_uv_sphere(builder, 0.043, warm, 12, 20)),
        "CommsCable": mesh("CommsCable", add_cylinder(builder, 0.012, 0.36, leather, 8)),
    }

    nodes: list[dict] = [{"name": "MechromancerModel", "children": [], "extras": {"ironwright_asset_id": "mechromancer.player.v1"}}]

    def add_node(
        name: str,
        mesh_id: int | None = None,
        translation: Sequence[float] = (0.0, 0.0, 0.0),
        rotation: Sequence[float] = (0.0, 0.0, 0.0),
        extras: dict | None = None,
        parent: int = 0,
    ) -> int:
        entry: dict = {"name": name, "translation": list(translation)}
        if mesh_id is not None:
            entry["mesh"] = mesh_id
        if rotation != (0.0, 0.0, 0.0):
            entry["rotation"] = quat(rotation)
        if extras:
            entry["extras"] = extras
        nodes.append(entry)
        nodes[parent].setdefault("children", []).append(len(nodes) - 1)
        return len(nodes) - 1

    torso = add_node("Torso", mesh_ids["Torso"], (0.0, 1.28, 0.0))
    add_node("ChestShell", mesh_ids["ChestShell"], (0.0, 1.36, 0.22))
    add_node("ChestArmorPlate", mesh_ids["ChestArmorPlate"], (0.0, 1.37, 0.325))
    add_node("ChestPlate", mesh_ids["ChestPlate"], (0.0, 1.43, -0.22))
    add_node("Scarf", mesh_ids["Scarf"], (0.0, 1.69, 0.0))
    add_node("Hood", mesh_ids["Hood"], (0.0, 1.88, 0.03))
    add_node("FaceAnchor", None, (0.0, 1.84, -0.25), extras={"socket_type": "face_anchor"})
    add_node("Face", mesh_ids["Face"], (0.0, 1.84, -0.25))
    add_node("Visor", mesh_ids["Visor"], (0.0, 1.88, -0.325))
    add_node("LeftShoulder", mesh_ids["Shoulder"], (-0.37, 1.52, 0.0), (0.0, 0.0, -0.08))
    add_node("RightShoulder", mesh_ids["Shoulder"], (0.37, 1.52, 0.0), (0.0, 0.0, 0.08))
    add_node("FieldPack", mesh_ids["Pack"], (0.0, 1.20, 0.24), extras={"socket_type": "equipment_mount"})
    add_node("PackPlate", mesh_ids["PackPlate"], (0.0, 1.25, 0.135))
    add_node("UtilityBelt", mesh_ids["Belt"], (0.0, 1.03, -0.02))
    add_node("LeftArm", mesh_ids["Arm"], (-0.43, 1.27, -0.01), (0.0, 0.0, -0.10))
    add_node("RightArm", mesh_ids["Arm"], (0.43, 1.27, -0.01), (0.0, 0.0, 0.10))
    add_node("LeftGlove", mesh_ids["Glove"], (-0.46, 1.00, -0.08), (math.pi * 0.5, 0.0, 0.0))
    add_node("RightGlove", mesh_ids["Glove"], (0.46, 1.00, -0.08), (math.pi * 0.5, 0.0, 0.0))
    add_node("LeftLeg", mesh_ids["Leg"], (-0.19, 0.56, 0.0))
    add_node("RightLeg", mesh_ids["Leg"], (0.19, 0.56, 0.0))
    add_node("LeftBoot", mesh_ids["Boot"], (-0.19, 0.17, -0.08))
    add_node("RightBoot", mesh_ids["Boot"], (0.19, 0.17, -0.08))
    add_node("CoatTailLeft", mesh_ids["CoatTail"], (-0.18, 0.69, 0.13), (0.0, 0.0, -0.045))
    add_node("CoatTailRight", mesh_ids["CoatTail"], (0.18, 0.69, 0.13), (0.0, 0.0, 0.045))
    add_node("ShoulderLamp", mesh_ids["LampHousing"], (-0.42, 1.58, -0.16), extras={"socket_type": "light_mount"})
    add_node("LampCore", mesh_ids["Lamp"], (-0.42, 1.58, -0.245))
    add_node("FieldCommsYoke", mesh_ids["CommsYoke"], (0.44, 1.60, -0.12), (0.0, 0.14, 0.0))
    add_node("FieldCommsAntenna", mesh_ids["CommsAntenna"], (0.49, 1.60, 0.00), (0.0, 0.44, 0.0))
    add_node("FieldCommsBeacon", mesh_ids["CommsBeacon"], (0.60, 1.60, 0.02))
    add_node("FieldCommsCable", mesh_ids["CommsCable"], (0.31, 1.46, -0.02), (0.0, 0.0, -0.82))
    add_node("WarmLamp", mesh_ids["WarmLamp"], (0.31, 1.52, -0.20))
    pistol = add_node("WeakPistol", mesh_ids["Pistol"], (0.48, 1.12, -0.27), extras={"socket_type": "weapon_mount"})
    add_node("PistolBarrel", mesh_ids["Barrel"], (0.0, 0.0, -0.27), (math.pi * 0.5, 0.0, 0.0), parent=pistol)
    add_node("PistolMuzzle", None, (0.0, 0.0, -0.42), extras={"socket_type": "weapon_muzzle"}, parent=pistol)
    add_node("FieldTool", mesh_ids["Tool"], (-0.29, 1.17, -0.22), (0.0, 0.0, -0.16))
    add_node("ProductionAssetMarker", None, extras={"asset_contract": "mechromancer.player.v1"})

    node_index = {node["name"]: index for index, node in enumerate(nodes)}

    def animation(name: str, channels: list[tuple[str, str, list[float], list[float], str]]) -> dict:
        samplers: list[dict] = []
        output_type = {"translation": ("VEC3", 3), "rotation": ("VEC4", 4), "scale": ("VEC3", 3)}
        channel_entries: list[dict] = []
        for target_name, path, times, values, interpolation in channels:
            time_accessor = builder.accessor(times, 5126, "SCALAR", len(times), minimum=[min(times)], maximum=[max(times)])
            type_name, width = output_type[path]
            output_accessor = builder.accessor(values, 5126, type_name, len(values) // width)
            sampler_index = len(samplers)
            samplers.append({"input": time_accessor, "output": output_accessor, "interpolation": interpolation})
            channel_entries.append({"sampler": sampler_index, "target": {"node": node_index[target_name], "path": path}})
        return {"name": name, "samplers": samplers, "channels": channel_entries}

    animations = [
        animation("Idle", [
            ("MechromancerModel", "translation", [0.0, 0.8, 1.6], [0.0, 0.0, 0.0, 0.0, 0.012, 0.0, 0.0, 0.0, 0.0], "LINEAR"),
            ("Hood", "translation", [0.0, 0.8, 1.6], [0.0, 1.88, 0.03, 0.0, 1.892, 0.03, 0.0, 1.88, 0.03], "LINEAR"),
            ("FieldPack", "translation", [0.0, 0.8, 1.6], [0.0, 1.20, 0.24, 0.0, 1.21, 0.24, 0.0, 1.20, 0.24], "LINEAR"),
            ("FieldCommsAntenna", "rotation", [0.0, 0.8, 1.6], quat((0.0, -0.035, 0.0)) + quat((0.0, 0.045, 0.0)) + quat((0.0, -0.035, 0.0)), "LINEAR"),
            ("FieldCommsBeacon", "translation", [0.0, 0.8, 1.6], [0.60, 1.60, 0.02, 0.60, 1.615, 0.02, 0.60, 1.60, 0.02], "LINEAR"),
        ]),
        animation("Walk", [
            ("LeftLeg", "rotation", [0.0, 0.22, 0.44], quat((0.24, 0.0, 0.0)) + quat((-0.24, 0.0, 0.0)) + quat((0.24, 0.0, 0.0)), "LINEAR"),
            ("RightLeg", "rotation", [0.0, 0.22, 0.44], quat((-0.24, 0.0, 0.0)) + quat((0.24, 0.0, 0.0)) + quat((-0.24, 0.0, 0.0)), "LINEAR"),
            ("CoatTailLeft", "rotation", [0.0, 0.22, 0.44], quat((0.08, 0.0, -0.045)) + quat((0.22, 0.0, -0.045)) + quat((0.08, 0.0, -0.045)), "LINEAR"),
            ("CoatTailRight", "rotation", [0.0, 0.22, 0.44], quat((0.08, 0.0, 0.045)) + quat((0.22, 0.0, 0.045)) + quat((0.08, 0.0, 0.045)), "LINEAR"),
            ("FieldPack", "translation", [0.0, 0.22, 0.44], [0.0, 1.20, 0.24, 0.0, 1.25, 0.24, 0.0, 1.20, 0.24], "LINEAR"),
            ("FieldCommsAntenna", "rotation", [0.0, 0.22, 0.44], quat((0.0, 0.0, -0.02)) + quat((0.0, 0.0, 0.05)) + quat((0.0, 0.0, -0.02)), "LINEAR"),
        ]),
        animation("Fire", [
            ("WeakPistol", "translation", [0.0, 0.08, 0.18], [0.48, 1.12, -0.27, 0.48, 1.12, -0.35, 0.48, 1.12, -0.27], "LINEAR"),
            ("RightArm", "rotation", [0.0, 0.08, 0.18], quat((0.0, 0.0, 0.10)) + quat((0.0, 0.0, 0.04)) + quat((0.0, 0.0, 0.10)), "LINEAR"),
            ("ShoulderLamp", "rotation", [0.0, 0.08, 0.18], quat((0.0, 0.0, 0.0)) + quat((0.0, 0.08, 0.0)) + quat((0.0, 0.0, 0.0)), "LINEAR"),
            ("FieldCommsAntenna", "rotation", [0.0, 0.08, 0.18], quat((0.0, 0.0, 0.0)) + quat((0.0, -0.08, 0.0)) + quat((0.0, 0.0, 0.0)), "LINEAR"),
        ]),
        animation("Work", [
            ("LeftArm", "rotation", [0.0, 0.5, 1.0], quat((0.0, 0.0, -0.10)) + quat((-0.65, 0.0, -0.25)) + quat((0.0, 0.0, -0.10)), "LINEAR"),
            ("RightArm", "rotation", [0.0, 0.5, 1.0], quat((0.0, 0.0, 0.10)) + quat((-0.72, 0.0, 0.25)) + quat((0.0, 0.0, 0.10)), "LINEAR"),
            ("FieldTool", "rotation", [0.0, 0.5, 1.0], quat((0.0, 0.0, -0.16)) + quat((0.0, 0.0, -0.34)) + quat((0.0, 0.0, -0.16)), "LINEAR"),
            ("FieldCommsYoke", "rotation", [0.0, 0.5, 1.0], quat((0.0, 0.14, 0.0)) + quat((0.0, 0.22, 0.0)) + quat((0.0, 0.14, 0.0)), "LINEAR"),
            ("FieldCommsAntenna", "rotation", [0.0, 0.5, 1.0], quat((0.0, 0.0, 0.0)) + quat((0.0, 0.10, 0.0)) + quat((0.0, 0.0, 0.0)), "LINEAR"),
        ]),
        animation("Upgrade", [
            ("LeftArm", "rotation", [0.0, 0.5, 1.0], quat((0.0, 0.0, -0.10)) + quat((-0.82, 0.0, -0.28)) + quat((0.0, 0.0, -0.10)), "LINEAR"),
            ("RightArm", "rotation", [0.0, 0.5, 1.0], quat((0.0, 0.0, 0.10)) + quat((-0.88, 0.0, 0.28)) + quat((0.0, 0.0, 0.10)), "LINEAR"),
            ("FieldTool", "rotation", [0.0, 0.5, 1.0], quat((0.0, 0.0, -0.16)) + quat((0.0, 0.0, -0.48)) + quat((0.0, 0.0, -0.16)), "LINEAR"),
            ("FieldCommsAntenna", "rotation", [0.0, 0.5, 1.0], quat((0.0, 0.0, 0.0)) + quat((0.0, -0.12, 0.0)) + quat((0.0, 0.0, 0.0)), "LINEAR"),
        ]),
        animation("Hit", [
            ("MechromancerModel", "rotation", [0.0, 0.08, 0.24], quat((0.0, 0.0, 0.0)) + quat((0.10, 0.0, 0.05)) + quat((0.0, 0.0, 0.0)), "LINEAR"),
            ("FieldPack", "rotation", [0.0, 0.08, 0.24], quat((0.0, 0.0, 0.0)) + quat((0.0, -0.08, 0.0)) + quat((0.0, 0.0, 0.0)), "LINEAR"),
            ("CoatTailLeft", "rotation", [0.0, 0.08, 0.24], quat((0.0, 0.0, -0.045)) + quat((0.10, 0.0, -0.045)) + quat((0.0, 0.0, -0.045)), "LINEAR"),
        ]),
    ]

    document = {
        "asset": {"version": "2.0", "generator": "Project Ironwright original Mechromancer asset builder"},
        "scene": 0,
        "scenes": [{"name": "Mechromancer", "nodes": [0]}],
        "nodes": nodes,
        "meshes": meshes,
        "materials": materials,
        "accessors": builder.accessors,
        "bufferViews": builder.views,
        "buffers": [{"byteLength": len(builder.data), "uri": "data:application/octet-stream;base64," + base64.b64encode(builder.data).decode("ascii")}],
        "animations": animations,
        "extras": {
            "ironwright_asset_id": "mechromancer.player.v1",
            "required_nodes": ["MechromancerModel", "PistolMuzzle", "ShoulderLamp", "FaceAnchor", "FieldPack", "FieldCommsYoke", "FieldCommsAntenna", "FieldCommsBeacon", "FieldCommsCable", "CoatTailLeft", "CoatTailRight"],
            "animation_clips": ["Idle", "Walk", "Fire", "Work", "Upgrade", "Hit"],
        },
    }
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(json.dumps(document, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
